apiVersion: v1
kind: Service # Type of the kubernetes resource
metadata:
  name: nextjs-frontend # Name of the Kubernetes resource
  labels: # Labels that will be applied to the resource
    app: nextjs-frontend
spec:
  type: NodePort # Gives each node an external IP that’s accessible from outside the cluster and also opens a Port.
  selector:
    app: nextjs-frontend # Selects any Pod with labels `app=nextjs-frontend`
  ports:
    - name: http
      port: 3000
      targetPort: 3000
